dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
install:
  - bash build_tools/travis/install_script.sh

# command to run tests
# Push to test
script:
  -  pytest
